#!/usr/bin/env python3
"""Bootstrap a Matrix bot account on mtrx.shaperotator.xyz.

Idempotent: re-runs reuse an existing bot.env instead of minting another
account. Failures are recoverable without admin help — bot.env stores the
password so deactivate.py can self-clean.

Flow (mirrors tests/sas_prod.py against prod, validated PASS):
  1. signup (only if no bot.env yet)
  2. fetch responder.py + sas_verification.py
  3. launch responder.py as a child process, wait until it logs "responder up"
  4. wait a few seconds so share_keys() finishes publishing device keys
  5. POST /signup/api/crosssign — server signs the device with the SSK it
     just generated; device_signed must come back True
  6. leave responder running so SAS verification (clicked in Element) works

Usage:
    python3 bootstrap.py --code <signup-code> --username <localpart> \\
                        --workdir ~/.local/share/shape-rotator-bot

Env override: HS=https://other to point at a non-prod homeserver.
"""
import argparse, json, os, secrets, shlex, signal, string, subprocess, sys, time, urllib.parse, urllib.request, urllib.error
from pathlib import Path


def http(method, url, body=None, token=None):
    headers = {"Content-Type": "application/json"}
    if token:
        headers["Authorization"] = f"Bearer {token}"
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=30) as r:
            return r.status, json.loads(r.read() or b"{}")
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read() or b"{}")


def parse_env(path):
    out = {}
    for line in path.read_text().splitlines():
        if line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        if v.startswith("'") and v.endswith("'"):
            v = v[1:-1].replace("'\"'\"'", "'")
        out[k] = v
    return out


def write_env(path, env):
    def q(v): return shlex.quote(str(v))
    body = "# Generated by matrix-bot-setup. KEEP THIS FILE PRIVATE.\n"
    body += "# TOKEN grants speak-as-bot. BOT_PASSWORD lets deactivate.py self-clean.\n"
    for k, v in env.items():
        body += f"{k}={q(v)}\n"
    path.write_text(body)
    path.chmod(0o600)


def wait_for_responder_up(proc, log_path, timeout=60):
    """Tail the responder log until we see the 'responder up' marker,
    or until the process dies. Returns True on success."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        if proc.poll() is not None:
            return False
        if log_path.exists():
            for line in log_path.read_text().splitlines():
                if line.startswith("responder up as "):
                    return True
        time.sleep(0.5)
    return False


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--code",     help="signup code (required for first run)")
    ap.add_argument("--username", help="bot localpart, e.g. 'andrew-bot' (required for first run)")
    ap.add_argument("--display",  default="", help="display name (default: same as username)")
    ap.add_argument("--workdir",  required=True, type=Path,
                    help="where credentials, responder.py, crypto db will live")
    args = ap.parse_args()

    HS = os.environ.get("HS", "https://mtrx.shaperotator.xyz").rstrip("/")
    args.workdir.mkdir(parents=True, exist_ok=True)
    env_path = args.workdir / "bot.env"

    # --- Step 1: signup (or reuse existing) ---
    fresh_signup = False
    if env_path.exists():
        env = parse_env(env_path)
        print(f"[1/5] reusing existing {env_path}")
        print(f"  user_id  = {env['MXID']}")
        print(f"  device   = {env['DEVICE']}")
    else:
        if not args.code or not args.username:
            sys.exit("first run requires --code and --username")
        password = "".join(secrets.choice(string.ascii_letters + string.digits) for _ in range(32))
        print(f"[1/5] signing up @{args.username} on {HS}")
        st, r = http("POST", f"{HS}/signup/api", {
            "code":         args.code,
            "username":     args.username,
            "password":     password,
            "display_name": args.display or args.username,
            "intro":        "",   # The auto-DM intro path triggers a prod-responder bug
        })                          # (responder.py line 132 — resp.event_id on a str).
        if st != 200:                # We skip it; federation warms via share_keys() alone.
            sys.exit(f"  signup failed ({st}): {r}")
        env = {
            "HS":           HS,
            "MXID":         r["user_id"],
            "TOKEN":        r["access_token"],
            "DEVICE":       r["device_id"],
            "STORE":        str(args.workdir / "bot_crypto.db"),
            # Deliberately omit DM_ROOM/INTRO — they activate the broken auto-post.
            "BOT_PASSWORD": password,
        }
        write_env(env_path, env)
        fresh_signup = True
        print(f"  user_id  = {env['MXID']}")
        print(f"  device   = {env['DEVICE']}")
        print(f"  credentials → {env_path} (mode 0600)")

    # --- Step 2: fetch responder + sas_verification ---
    print(f"[2/5] fetching responder.py + sas_verification.py")
    for fname in ("responder.py", "sas_verification.py"):
        target = args.workdir / fname
        with urllib.request.urlopen(f"{HS}/{fname}", timeout=15) as resp:
            target.write_bytes(resp.read())

    # --- Step 3: launch responder as child, wait for "responder up" ---
    print(f"[3/5] launching responder")
    log_path = args.workdir / "responder.log"
    if log_path.exists():
        log_path.unlink()
    proc_env = {**os.environ, **env}
    proc = subprocess.Popen(
        [sys.executable, "-u", str(args.workdir / "responder.py")],
        cwd=str(args.workdir),
        env=proc_env,
        stdout=open(log_path, "w"),
        stderr=subprocess.STDOUT,
        start_new_session=True,
    )
    print(f"  pid={proc.pid} log={log_path}")
    if not wait_for_responder_up(proc, log_path):
        print(f"  responder did not come up; log:", file=sys.stderr)
        print(log_path.read_text()[-2000:] if log_path.exists() else "(no log)",
              file=sys.stderr)
        proc.terminate()
        sys.exit(1)
    print(f"  responder up; waiting 8s for share_keys() to publish device keys")
    time.sleep(8)

    # --- Step 4: crosssign (only on first-run; the endpoint is single-shot
    #     per account, so idempotent re-runs skip it). Device keys are now
    #     uploaded, so the server-side handler can sign the device with the
    #     SSK it generates. ---
    if fresh_signup:
        print(f"[4/5] cross-signing")
        st, cs = http("POST", f"{HS}/signup/api/crosssign",
                      {"access_token": env["TOKEN"]})
        if st != 200:
            print(f"  crosssign HTTP {st}: {cs}", file=sys.stderr)
            print(f"  /signup/api/crosssign is single-shot per account. Run",
                  file=sys.stderr)
            print(f"  deactivate.py and re-bootstrap with a new username.",
                  file=sys.stderr)
            proc.terminate()
            sys.exit(1)
        if not cs.get("device_signed"):
            print(f"  WARNING: device_signed=False. Outbound encrypted send will",
                  file=sys.stderr)
            print(f"  fail. Response: {cs}", file=sys.stderr)
            proc.terminate()
            sys.exit(1)
        print(f"  msk = {cs['msk_public'][:24]}...")
        print(f"  device_signed = True")
    else:
        print(f"[4/5] skipping cross-signing (already done on first run)")

    # --- Step 5: stay running as the bot ---
    print(f"[5/5] bot is live. To verify:")
    print(f"      → open Element on your existing Matrix account")
    print(f"      → start a new DM with {env['MXID']}")
    print(f"      → click their profile → Verify → match emoji → 'they match'")
    print(f"")
    print(f"responder pid {proc.pid} — Ctrl-C to stop (the bot stays registered)")
    print(f"to wipe entirely: python3 deactivate.py {env_path}")

    # Forward signals so Ctrl-C cleanly stops the child.
    def _stop(*_): proc.terminate()
    signal.signal(signal.SIGINT, _stop)
    signal.signal(signal.SIGTERM, _stop)
    proc.wait()


if __name__ == "__main__":
    main()
